import { ABILITY_TYPE, BUFF_TYPE, ELEMENT, EVENT_TYPE, PHYSICAL_STATUS } from "../data/constants.js";

/**
 * Simulation events processed by the Engine during simulation.
 * The only event added by user input is SkillEvent. Every other event is internally generated as intermediaries.
 */
class SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority Used to break ties in case of identical time values. The smaller the value, the greater its priority.
     * @param {string} sourceId 
     * @param {string} targetId 
     */
    constructor(time, priority, sourceId, targetId) {
        this.time = time;
        this.priority = priority;
        this.type = null;
        this.sourceId = sourceId;
        this.targetId = targetId;
        this.data = null; // every event will have its payload enclosed in a data field
    }
}
/**
 * A single instance of damage. Skills will be deconstructed into individual hit events for each strike.
 */
export class HitEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {number} mv 
     * @param {ELEMENT} element 
     * @param {number} stagger 
     * @param {ABILITY_TYPE} hitType 
     * @param {number} hitIndex optional metadata: which hit in the sequence is this?
     */
    constructor(time, priority, sourceId, targetId, mv, element, stagger, hitType, hitIndex) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.HIT;
        this.data = { mv, element, stagger, hitType, hitIndex };
    }
}

/**
 * An instance of an Arts Infliction being applied.
 */
export class InflictionEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {ELEMENT} element The element being inflicted
     */
    constructor(time, priority, sourceId, targetId, element) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.ARTS_INFLICTION;
        this.data = { element };
    }
}

/**
 * An instance of a Physical Status being applied.
 */
export class PhysicalEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {PHYSICAL_STATUS} type 
     */
    constructor(time, priority, sourceId, targetId, type) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.PHYSICAL_APPLICATION;
        this.data = { type };
    }
}

/**
 * An instance of a status effect being applied. Does not matter if it is a buff, debuff or neutral.
 */
export class ApplyStatus extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} statusId 
     * @param {number} duration 
     * @param {number} value 
     * @param {BUFF_TYPE} type 
     * @param {*} subtype 
     */
    constructor(time, priority, sourceId, targetId, statusId, duration, value, type, subtype) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.STATUS_APPLICATION;
        this.data = { statusId, duration, value, type, subtype };
    }
}

/**
 * A buff ending.
 * * Strictly generated by StatusComponents only, upon application of a buff.
 */
export class EndStatus extends SimEvent {
    constructor(time, priority, sourceId, targetId, statusId, type, subtype) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.STATUS_EXPIRATION;
        this.data = { type, subtype };
    }
}

/**
 * Generated by the user adding a skill event to the timeline.
 */
export class SkillEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {ABILITY_TYPE} type 
     */
    constructor(time, priority, sourceId, targetId, type) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.SKILL_EVENT;
        this.data = { type };
    }
}

/**
 * Used when a change needs to be made to something in the combat state.
 */
export class StateUpdate extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} property 
     * @param {number} value 
     */
    constructor(time, priority, sourceId, targetId, property, value) {
        super(time, priority, sourceId, targetId);
        this.type = EVENT_TYPE.STATE_UPDATE;
        this.data = { property, value };
    }
}