import { ABILITY_TYPE, BUFF_TYPE, ELEMENT, EVENT_TYPE, PHYSICAL_STATUS } from "../data/constants.js";

/**
 * Simulation events processed by the Engine during simulation.
 * The only event added by user input is SkillEvent. Every other event is internally generated as intermediaries.
 * Every event contains the following fields:
 * - time and priority for sorting in the EventQueue
 * - the IDs of the source and target of the event
 * - a data field containing relevant information used in calculations/processing. every subfield here must be filled (and can be assumed to exist).
 * - a tags field to allow for specific event checking. there is currently no exhaustive list of tags, just use as needed. optional.
 * - a metadata field for logging purposes. optional.
 */
class SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority Used to break ties in case of identical time values. The smaller the value, the greater its priority.
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, optionalData, tags, metadata) {
        this.time = time;
        this.priority = priority;
        this.type = null;
        this.sourceId = sourceId;
        this.targetId = targetId;
        this.data = null; // payload. all subfields must exist and be valid.
        this.optionalData = optionalData;
        this.tags = tags; // for trigger checking. optional.
        this.metadata = metadata; // for logging. optional.
    }
}
/**
 * A single instance of damage. Skills will be deconstructed into individual hit events for each strike.
 */
export class HitEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {ABILITY_TYPE | string} hitType
     * @param {number} mv 
     * @param {ELEMENT} element 
     * @param {number} stagger 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, hitType, mv, element, stagger, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.HIT;
        this.data = { hitType, mv, element, stagger };
    }
}

/**
 * An instance of an Arts Infliction being applied.
 */
export class InflictionEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {ELEMENT} element The element being inflicted
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, element, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.ARTS_INFLICTION;
        this.data = { element };
    }
}

/**
 * An instance of a Physical Status being applied.
 */
export class PhysicalEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {PHYSICAL_STATUS} type 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, type, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.PHYSICAL_APPLICATION;
        this.data = { type };
    }
}

/**
 * An instance of a status effect being applied. Does not matter if it is a buff, debuff or neutral.
 */
export class ApplyStatusEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} statusName
     * @param {string} namespace
     * @param {Object} optionalData 
     * @param {Set<string>} tags Do check out the STATUS_TYPE constants, will be useful.
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, statusName, namespace, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.STATUS_APPLICATION;
        this.data = { statusName, namespace };
        // fields like (base) duration or type should be left in the definition of the status
    }
}

/**
 * A buff ending.
 * * Strictly generated by StatusComponents only, upon application of a buff.
 */
export class EndStatusEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} statusId 
     * @param {boolean} isValid The StatusComponent may use this to invalidate certain packets (e.g. if an effect is purged or extended)
     * @param {BUFF_TYPE} type 
     * @param {*} subtype 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, statusId, isValid, type, subtype, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.STATUS_EXPIRATION;
        this.data = { isValid, type, subtype };
    }
}

/**
 * Used to support discrete ticking status effects.
 */
export class StatusTickEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} statusId 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, statusId, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.STATUS_TICK;
        this.data = { statusId };
    }
}

/**
 * Generated by the user adding a skill event to the timeline.
 */
export class SkillEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {ABILITY_TYPE} type 
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, type, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.SKILL_EVENT;
        this.data = { type };
    }
}

/**
 * Used when a change needs to be made to something in the combat state.
 */
export class StateUpdateEvent extends SimEvent {
    /**
     * @param {number} time 
     * @param {number} priority 
     * @param {string} sourceId 
     * @param {string} targetId 
     * @param {string} property 
     * @param {number} value 
     * @param {*} modifierType
     * @param {*} modifierId
     * @param {boolean} isRemoval
     * @param {Object} optionalData
     * @param {Set<string>} tags
     * @param {Object} metadata
     */
    constructor(time, priority, sourceId, targetId, property, value, modifierType, modifierId, isRemoval, optionalData, tags, metadata) {
        super(time, priority, sourceId, targetId, optionalData, tags, metadata);
        this.type = EVENT_TYPE.STATE_UPDATE;
        this.data = { property, value, modifierType, modifierId, isRemoval };
    }
}